### ISSUE TITLE
How to change the URL address of a WSDL port at runtime?

### ISSUE THREAD

**Issue by antoniosignore** [playframework/play-soap#237]
How to change the URL address of a WSDL port at runtime?

-----------
In the documentation it is documented how to change the address by setting a property configuration value:
<wsdl:service name="HelloWorldService">
    <wsdl:port binding="tns:HelloWorldSoapBinding" name="HelloWorld">
      <soap:address location="http://example.com/helloWorld"/>
    </wsdl:port>
</wsdl:service>
to change the address we need to add a configuration value:
play.soap.services.com.example.HelloWorldService.address = "http://example.com/helloWorld"
In our use case we cannot use a static value in the application.conf and need to change the address at runtime because we need to add a country suffix which we know at runtime:
"http://example.com/helloWorld/RO"
"http://example.com/helloWorld/SI"
...
I have tried unsuccesfully to add a JAX-WS handler to do so like:

   public boolean handleMessage(SOAPMessageContext context) {
        //Set timeout until a connection is established
        context.put("javax.xml.ws.client.connectionTimeout", "5000");
        context.put("javax.xml.ws.client.receiveTimeout", "5000");
        String countryAddress = configuration.getBydUrl() + countryCode;
        context.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, countryAddress);
        .....
        .....

What is the approach to follow for a solution in Java?

As a workaround I have for now an ugly working workaround where I have added in the WSDL one service
with a specific address per each remote tenant:
    <wsdl:service name="service_RO">
        <wsdl:port name="binding_SOAP12_RO" binding="tns:binding_SOAP12">
            <wsoap12:address
                    location="https://hc-apigw-d-internal.hilti.com/internal-generic/hc/MaintainLeadByDAdapter/v1/RO"/>
        </wsdl:port>
    </wsdl:service>
    <wsdl:service name="service_SI">
        <wsdl:port name="binding_SOAP12_SI" binding="tns:binding_SOAP12">
            <wsoap12:address
                    location="https://hc-apigw-d-internal.hilti.com/internal-generic/hc/MaintainLeadByDAdapter/v1/SI"/>
        </wsdl:port>
    </wsdl:service>

and then with an ugly factory I return the SOAP operation per country: 
....
   private final ServiceVN serviceVN;
    private final ServiceUA serviceUA;
...
    Optional <MaintainLeadIn> getMaintainLeadIn(String countryCode){
        switch (countryCode){
            case "SI": return Optional.of(serviceSI.getBindingSOAP12SI());
            case "BA": return Optional.of(serviceBA.getBindingSOAP12BA());
.....

but it is not ideal because for each new tenant I need to rebuild the service which I would like
to avoid.

**Comment by ihostage** [comment]
Hi @antoniosignore! How did you add your SOAP message handler?

**Comment by ihostage** [comment]
Also, I see in your code custom timeout settings. Please, read my answer on #228 for known how you can do that.

**Comment by antoniosignore** [comment]
> Hi @antoniosignore! How did you add your SOAP message handler?

        MaintainLeadIn bindingSOAP12 = service.getBindingSOAP12RO(new services.sap.Handler(applicationConfiguration, countryCode));

**Comment by antoniosignore** [comment]
> Also, I see in your code custom timeout settings. Please, read my answer on #228 for known how you can do that.

I did see that answer, but how to I change the URL address of the port?

**Comment by antoniosignore** [comment]
> Also, I see in your code custom timeout settings. Please, read my answer on #228 for known how you can do that.

Trying this:

 PlayJaxWsClientProxy proxy = (PlayJaxWsClientProxy) Proxy.getInvocationHandler(service);
        EndpointReferenceType target = proxy.getClient().getConduit().getTarget();
        AttributedURIType value = new AttributedURIType();
        value.setValue(applicationConfiguration.getBydUrl() + countryCode);
        target.setAddress(value);

**Comment by antoniosignore** [comment]
> Also, I see in your code custom timeout settings. Please, read my answer on #228 for known how you can do that.

No joy.

java.lang.IllegalArgumentException: not a proxy instance

	at java.lang.reflect.Proxy.getInvocationHandler(Proxy.java:816)
	at services.sap.SOAPClient.sendLead(SOAPClient.java:116)

**Comment by ihostage** [comment]
Hello, @antoniosignore! 
One of our tasks needed the same logic. We added a special handler in our library. You can see very easy implementation in [this class](https://github.com/taymyr/lagom-soap-client/blob/0cc48036a15ba75ca477f43cd37e0d48fc18fca5/java/src/main/kotlin/org/taymyr/lagom/soap/handler/EndpointAddressHandler.kt#L16).

For you it's will look like this:
```java
MaintainLeadIn service = service.getBindingSOAP12RO(...);
((BindingProvider) service).getRequestContext()
    .put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8080/foobar");
```
