### ISSUE TITLE
Not able to set "-exsh true" for wsdl2java args

### ISSUE THREAD

**Issue by akprats33** [playframework/play-soap#40]
Play version  `2.6.5`
Play soap version `1.1.3`
Scala version `2.11.11`

When I pass `-exsh true` to `wsdlArgs` I am getting `unexpected option` error. I have tested the wsdl file separately with `wsdl2java` while passing the same argument. It is working fine there. 

Code for passing the arguments - 

```
// additional arguments to wsdl2java
WsdlKeys.wsdlToCodeArgs ++= Seq(
  "-exsh true"
)
```

 Following is the stack trace -

```
org.apache.cxf.tools.common.ToolException: org.apache.cxf.tools.common.toolspec.parser.BadUsageException: Unexpected option: -exsh true

	at org.apache.cxf.tools.common.toolspec.AbstractToolContainer.execute(AbstractToolContainer.java:180)
	at org.apache.cxf.tools.common.AbstractCXFToolContainer.execute(AbstractCXFToolContainer.java:69)
	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:414)
	at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2$$anonfun$3.apply(SbtWsdl.scala:216)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2$$anonfun$3.apply(SbtWsdl.scala:189)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2.apply(SbtWsdl.scala:189)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2.apply(SbtWsdl.scala:187)
	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2.apply(SbtWsdl.scala:187)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2.apply(SbtWsdl.scala:184)
	at play.soap.sbtplugin.SbtWsdl$.play$soap$sbtplugin$SbtWsdl$$withContextClassLoader(SbtWsdl.scala:275)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1.apply(SbtWsdl.scala:184)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1.apply(SbtWsdl.scala:175)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.cxf.tools.common.toolspec.parser.BadUsageException: Unexpected option: -exsh true

	at org.apache.cxf.tools.common.toolspec.parser.CommandLineParser.throwUsage(CommandLineParser.java:201)
	at org.apache.cxf.tools.common.toolspec.parser.CommandLineParser.parseArguments(CommandLineParser.java:174)
	at org.apache.cxf.tools.common.toolspec.AbstractToolContainer.parseCommandLine(AbstractToolContainer.java:89)
	at org.apache.cxf.tools.common.toolspec.AbstractToolContainer.execute(AbstractToolContainer.java:178)
	at org.apache.cxf.tools.common.AbstractCXFToolContainer.execute(AbstractCXFToolContainer.java:69)
	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:414)
	at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2$$anonfun$3.apply(SbtWsdl.scala:216)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2$$anonfun$3.apply(SbtWsdl.scala:189)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2.apply(SbtWsdl.scala:189)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2$$anonfun$2.apply(SbtWsdl.scala:187)
	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2.apply(SbtWsdl.scala:187)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1$$anonfun$apply$2.apply(SbtWsdl.scala:184)
	at play.soap.sbtplugin.SbtWsdl$.play$soap$sbtplugin$SbtWsdl$$withContextClassLoader(SbtWsdl.scala:275)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1.apply(SbtWsdl.scala:184)
	at play.soap.sbtplugin.SbtWsdl$$anonfun$wsdlToCodeTask$1.apply(SbtWsdl.scala:175)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:wsdlToCode) org.apache.cxf.tools.common.ToolException: org.apache.cxf.tools.common.toolspec.parser.BadUsageException: Unexpected option: -exsh true

```

**Comment by akprats33** [comment]
I was using the wrong format to pass args. Following is the right way -

```
WsdlKeys.wsdlToCodeArgs ++= Seq(
  "-exsh", "true"
)
```
