### ISSUE TITLE
Could not find play frontend within classpath

### ISSUE THREAD

**Issue by cyrilfr** [playframework/play-soap#414]
I'm setting up play-soap to generate a SOAP client for the swiss eBill web service in a Play 2.8 app.

I added the last version of the `play-soap-client` (1.2.0) dependency to my build.sbt file and sbt-cxf 1.6 to my plugins.sbt file.

Here is the config:

```
cxfWSDLs := Seq(
  Wsdl(
    "eBillB2BService",
    (Compile / resourceDirectory).value / "wsdl/eBillB2BService.wsdl",
    Seq("-fe", "play", "-xjc-Xplay:lang java", "-xjc-Xplay:target play", "-autoNameResolution")
  )
)
```

the WSDL file can be downloaded from https://ebill-ki.postfinance.ch/B2BService/B2BService.svc?singleWsdl

When I try to compile, I get an error:

```
[info] WSDL: key=eBillB2BService, args=-d /my-app/common/target/scala-2.13/cxf/main -exsh true -validate -fe play -xjc-Xplay:lang java -xjc-Xplay:target play -autoNameResolution /my-app/common/conf/wsdl/eBillB2BService.wsdl
[info] Compiling WSDL...
[error] Failed to compile wsdl with exception: null
[error] stack trace is suppressed; run last common / Compile / run wsdl2java for the full output
[info] Compiled WSDL in 428ms.
```

The cause of this error is the `-fe play` param. When I remove it the error is gone but the generated code isn't the expected one.

When I run `last` in sbt, I get this output:

```
[error] Failed to compile wsdl with exception: null
[error] java.lang.reflect.InvocationTargetException
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.callWsdl2java(CxfPlugin.scala:143)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$6(CxfPlugin.scala:89)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$3(CxfPlugin.scala:87)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Caused by: org.apache.cxf.tools.common.ToolException: Could not find play frontend within classpath
[error] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEnd(PluginLoader.java:246)
[error] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEndProfile(PluginLoader.java:381)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.loadFrontEnd(WSDLToJava.java:64)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:96)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.callWsdl2java(CxfPlugin.scala:143)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$6(CxfPlugin.scala:89)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$3(CxfPlugin.scala:87)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)[error] Failed to compile wsdl with exception: null
[error] java.lang.reflect.InvocationTargetException
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.callWsdl2java(CxfPlugin.scala:143)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$6(CxfPlugin.scala:89)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$3(CxfPlugin.scala:87)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Caused by: org.apache.cxf.tools.common.ToolException: Could not find play frontend within classpath
[error] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEnd(PluginLoader.java:246)
[error] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEndProfile(PluginLoader.java:381)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.loadFrontEnd(WSDLToJava.java:64)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:96)
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.callWsdl2java(CxfPlugin.scala:143)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$6(CxfPlugin.scala:89)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at io.paymenthighway.sbt.cxf.CxfPlugin$.$anonfun$settings$3(CxfPlugin.scala:87)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

I tried to run `wsdl2java` manually but I cannot find the `play-soap-plugin.jar` file in the project as shown in the doc: https://playframework.github.io/play-soap/2.x/plugin/cli.html

**Comment by ihostage** [comment]
Hi, @cyrilfr! 
If you want to use Play SOAP 1.x you should follow the next documentation https://playframework.github.io/play-soap/1.x/index.html and use `sbt-play-soap` sbt plugin to generate. 
Just 2.x version isn't released yet and we need to do some tasks before we'll do that. But you already can use a SNAPSHOT version from OSS Sonatype repository (for example https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-soap-plugin/1.2.0+263-29eeee63-SNAPSHOT/). Just add this repo into your build script (for SBT see docs about resolvers https://www.scala-sbt.org/1.x/docs/Library-Management.html#Resolvers) and use SPAPSHOT version for `play-soap-plugin` instead of `2.0.0` like is showed in docs.

**Comment by cyrilfr** [comment]
I see. Thanks for your help, I really appreciate!
